import type { ActivityAlert } from '@/types';

export const RECENT_ACTIVITY: ActivityAlert[] = [
  {
    id: 'a1',
    timestamp: '14:32:18 UTC',
    domain: 'b8f3a1.acme-corp.io',
    sourceIp: '10.4.22.91',
    severity: 'Critical',
    class: 'Exfiltration',
    score: 0.92,
    action: 'Host isolated',
  },
  {
    id: 'a2',
    timestamp: '14:28:55 UTC',
    domain: 'login.microsoftonline.com',
    sourceIp: '10.4.18.204',
    severity: 'Low',
    class: 'Normal',
    score: -0.21,
    action: 'Logged',
  },
  {
    id: 'a3',
    timestamp: '14:21:07 UTC',
    domain: 'cdn-east.wealthgrid.net',
    sourceIp: '10.7.3.45',
    severity: 'Medium',
    class: 'Suspicious',
    score: 0.34,
    action: 'Flagged for review',
  },
  {
    id: 'a4',
    timestamp: '14:15:42 UTC',
    domain: 'x7q2kp.nimbus-data.app',
    sourceIp: '10.4.22.91',
    severity: 'High',
    class: 'Exfiltration',
    score: 0.74,
    action: 'Sinkholed',
  },
  {
    id: 'a5',
    timestamp: '14:09:30 UTC',
    domain: 'updates.ubuntu.com',
    sourceIp: '10.6.1.12',
    severity: 'Low',
    class: 'Normal',
    score: -0.15,
    action: 'Logged',
  },
  {
    id: 'a6',
    timestamp: '13:58:11 UTC',
    domain: 'mail-rly.titanfin.com',
    sourceIp: '10.9.14.7',
    severity: 'Medium',
    class: 'Suspicious',
    score: 0.28,
    action: 'Under observation',
  },
];
